"""Laser-induced breakdown spectroscopy / laser ablation analysis.

LIBS records emission lines (in nm) from plasma generated by a focused laser.
For gemological work the value is in **trace-element ratios** that fingerprint
geographic origin and growth method, not absolute concentration.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from checkmsg import preprocess
from checkmsg.peaks import Peak, detect
from checkmsg.refdata.nist_asd import AtomicLine, candidates_at
from checkmsg.spectrum import Spectrum


@dataclass
class ElementSignal:
    element: str
    matched_lines: list[AtomicLine] = field(default_factory=list)
    summed_height: float = 0.0


@dataclass
class LibsResult:
    peaks: list[Peak]
    elements: dict[str, ElementSignal]
    cleaned: Spectrum

    def has(self, element: str) -> bool:
        sig = self.elements.get(element)
        return bool(sig and sig.matched_lines)

    def height(self, element: str) -> float:
        sig = self.elements.get(element)
        return float(sig.summed_height) if sig else 0.0


def preprocess_libs(spectrum: Spectrum) -> Spectrum:
    if spectrum.technique != "libs":
        raise ValueError(f"expected libs spectrum, got {spectrum.technique}")
    baseline = preprocess.snip_baseline(spectrum.intensity, iterations=30)
    y_clean = np.clip(spectrum.intensity - baseline, 0, None)
    return spectrum.with_intensity(y_clean)


def identify(
    spectrum: Spectrum,
    tolerance_nm: float = 0.4,
    min_snr: float = 5.0,
) -> LibsResult:
    cleaned = preprocess_libs(spectrum)
    peaks = detect(cleaned, min_snr=min_snr)
    by_el: dict[str, ElementSignal] = {}
    for peak in peaks:
        for line in candidates_at(peak.position, tolerance_nm):
            sig = by_el.setdefault(line.element, ElementSignal(element=line.element))
            sig.matched_lines.append(line)
            sig.summed_height += peak.height * line.relative_intensity
    return LibsResult(peaks=peaks, elements=by_el, cleaned=cleaned)


def trace_ratios(result: LibsResult, pairs: list[tuple[str, str]]) -> dict[str, float]:
    """Compute element-to-element height ratios for a list of (numerator, denominator) pairs."""
    out: dict[str, float] = {}
    for num, den in pairs:
        n = result.height(num)
        d = result.height(den)
        out[f"{num}/{den}"] = float(n / d) if d > 0 else float("inf") if n > 0 else 0.0
    return out


def feature_vector(result: LibsResult, elements: list[str]) -> np.ndarray:
    """Stable feature vector of (log) heights for downstream classifiers."""
    arr = np.array([result.height(e) for e in elements], dtype=float)
    return np.log10(arr + 1e-6)
